require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  TargetRubyVersion: '3.1'
  Exclude:
    - sandbox/**/*
    - dummy-app/**/*
    - spec/dummy/**/*
    - vendor/bundle/**/*

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/VariableNumber:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
    - db/migrate/**/*
    - bin/**/*

Style/ExplicitBlockArgument:
  Exclude:
    - lib/solidus_braintree/request_protection.rb
